version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-contas-db-poc
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: contasapagar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  contasapagar:
    build: .
    container_name: contasapagar-app-poc
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/contasapagar
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  postgres-data: